export const data = [
    {
      id: 1,
      name: "Selling with re enter",
      calmar_Ratio: 3.96,
      overall_Profit: 381845,
      avgProfit: 319.54,
      win: 0.65,
      price: "-",
      action: "View",
    },
    {
      id: 2,
      name: "Selling with re enter",
      calmar_Ratio: 3.96,
      overall_Profit: 381845,
      avgProfit: 319.54,
      win: 0.65,
      price: "-",
      action: "Buy",
    },
    {
      id: 3,
      name: "Selling with re enter",
      calmar_Ratio: 3.96,
      overall_Profit: 381845,
      avgProfit: 319.54,
      win: 0.65,
      price: "-",
      action: "View",
    },
    {
      id: 4,
      name: "Selling with re enter",
      calmar_Ratio: 3.96,
      overall_Profit: 381845,
      avgProfit: 319.54,
      win: 0.65,
      price: "-",
      action: "View",
    },
    {
      id: 5,
      name: "Selling with re enter",
      calmar_Ratio: 3.96,
      overall_Profit: 381845,
      avgProfit: 319.54,
      win: 0.65,
      price: "-",
      action: "View",
    },
    {
      id: 6,
      name: "Selling with re enter",
      calmar_Ratio: 3.96,
      overall_Profit: 381845,
      avgProfit: 319.54,
      win: 0.65,
      price: "-",
      action: "View",
    },
    {
      id: 7,
      name: "Selling with re enter",
      calmar_Ratio: 3.96,
      overall_Profit: 381845,
      avgProfit: 319.54,
      win: 0.65,
      price: "-",
      action: "View",
    },
    {
      id: 8,
      name: "Selling with re enter",
      calmar_Ratio: 3.96,
      overall_Profit: 381845,
      avgProfit: 319.54,
      win: 0.65,
      price: "-",
      action: "View",
    },
  ];